#!/usr/bin/env python3
import os.path
import sys
DIR_ROOT = os.path.abspath(os.path.dirname(sys.argv[0]))
sys.path.append(os.path.join(DIR_ROOT))

import pytest

pytest.main(sys.argv[1:] + ["tests"])
